[feat] : 사용자는 회원가입을 할 수 있다
dev-hooon/interpark pull request #31
Opened 2023-12-23 19:38 UTC by ParkJuhan94

## 📄 무엇을 개발했나요? 
* 유저 엔티티 수정
* 회원가입 로직 구현

## 🍸 무엇을 집중적으로 리뷰해야할까요?
* User 엔티티의 생성자와 팩토리메서드를 만든 이유는 userMapper 에서 dto 를 엔티티로 변환하기 위함입니다~
* @PostMapping("/api/users/new") 는 Api 명세서와 다르게 만들어보았습니다. 원래 /api/auth 였는데,
   회원가입시에 인증인가는 필요없는 듯 해서 /api/users/new 가 어떨까 싶습니다.
* 그 외 어색한 부분이라든지, 리뷰 다 좋습니다

2023-12-24 05:41 UTC, EunChanNam requested changes
고생하셨습니다! 전체적으로 진짜 깔끔하게 잘 짜주신거같아요 👍
남긴 코멘트 말고 전체적으로 짚고 넘어갈게 몇가지 있는데,
1. 전체적인 테스트코드 : 레포지토리는 직접짠 쿼리가 없어서 괜찮을 것 같은데 엔티티나 서비스, api 통합테스트 추가 부탁드려요!
2. 비밀번호 암호화 : 비밀번호 암호화는 필수라서 암호화 라이브러리(아마 Bcrypt..?) 추가해서 암호화까지 추가하면 좋을 것 같아요

2023-12-24 05:41 UTC, EunChanNam commented on api/src/main/java/dev/hooon/user/UserApiController.java
> +@RequestMapping
해당 어노테이션은 필요없어보이네요!!

2023-12-24 05:41 UTC, EunChanNam commented on api/src/main/java/dev/hooon/user/UserApiController.java
> +@Slf4j
로깅하는 부분이 없는거 같은데 빼도 좋을거같아요~ ㅎㅎ

2023-12-24 05:41 UTC, EunChanNam commented on core/src/main/java/dev/hooon/user/dto/request/UserJoinRequestDto.java
> +public record UserJoinRequestDto(
Request 로 사용되는 DTO 네이밍은 Request 로 끝내기로 했던거같아요! 
수정 부탁드립니다~

2023-12-24 05:41 UTC, EunChanNam commented on core/src/main/java/dev/hooon/user/application/UserService.java
> +			throw new UserException(DUPLICATED_USER);
유저 중복검사를 할 때 List 로 조회하는 쿼리보다는 단건 조회로 Optional 을 활용하는건 어떨까요?

2023-12-24 05:41 UTC, EunChanNam commented on core/src/main/java/dev/hooon/user/domain/entity/User.java
> +	}
`UserRole` 에 대해서 파라미터로 받는 것도 좋지만 `ofBuyer` 같이 메소드 네이밍을 변경해서 `Buyer` 에 대한 생성만 담당하는 팩토리 메소드를 만들어서 파라미터로 `Role` 을 받지 않고 내부적으로 `Role` 을 할당하는 방식은 어떨까요? (단순 제 의견입니당 ㅎㅎ 편하게 의견주세요)

2023-12-24 05:41 UTC, EunChanNam commented on core/src/main/java/dev/hooon/user/dto/response/UserJoinResponseDto.java
> +public record UserJoinResponseDto(
여기도 마찬가지로 Response 네이밍으로 끝내도록 네이밍 수정 부탁드립니다~!

2023-12-24 05:41 UTC, EunChanNam commented on core/src/main/java/dev/hooon/user/exception/UserException.java
> +public class UserException extends RuntimeException {
저희 Exception 에 대해서는 도메인별 Exception 말고 공통의 Exception 으로 가져가기로 했던거 같아요. 
여기서 예를 들면 중복 검증에 대한 예외면 `ValidationException` 같은 공통 예외요! 
근데 아직 공통적으로 `ValidationException` 이 만들어지지 않아서 일단 이대로 머지하고 추후에 수정해도 괜찮을 것 같습니다!

2023-12-24 05:41 UTC, EunChanNam commented on core/src/main/java/dev/hooon/user/domain/entity/User.java
> +		this.userRole = userRole;
null 체크나 empty 체크 로직이 빠진것같아요!
Assert 메소드와 CommonValidationError 클래스 이용해서 null, empty 체크 코드 추가 부탁드려요~!

2023-12-24 05:42 UTC, EunChanNam commented on api/src/main/java/dev/hooon/user/UserApiController.java
> +@RequestMapping
여기서 해당 어노테이션은 `@RequestMapping` 입니다 ㅎㅎ 라인이 잘못 선택됐네요

2023-12-24 16:29 UTC, ssssujini99 approved these changes

2023-12-24 16:29 UTC, ssssujini99 commented on core/src/main/java/dev/hooon/user/application/UserService.java
> +			log.info(DUPLICATED_USER.getMessage());
로그는 안찍어도 될 것 같아요!
예외 던지는 부분에서 찍는걸로 정해가지구 ㅎㅎ

2023-12-24 16:29 UTC, ssssujini99 commented on core/src/main/java/dev/hooon/user/exception/UserException.java
> +public class UserException extends RuntimeException {
위 말대로 공용 예외로 만들고, UserErrorCode를 만드셔야 할 것 같아요!!

2023-12-24 16:29 UTC, ssssujini99 commented on core/src/main/java/dev/hooon/user/exception/UserErrorCode.java
👍🏻

2023-12-24 16:29 UTC, ssssujini99 commented on core/src/main/java/dev/hooon/user/domain/entity/UserMapper.java
> +	public static User toBuyerUser(UserJoinRequestDto userJoinRequestDto) {
buyerUser 가 어떤의미인지 여쭈어봐도 될까요??

2023-12-24 16:29 UTC, ssssujini99 commented on core/src/main/java/dev/hooon/user/domain/entity/User.java
> +		this.userRole = userRole;
validation 검증 로직이 빠진 것 같네요
위 코멘트랑 그리고 저희 email과 같은 경우 unique 제약조건이 있어서 이거 validation 체크도 꼼꼼히 해주셔야 할 것 같아용 ㅎㅎ

2023-12-26 01:03 UTC, ParkJuhan94 commented on core/src/main/java/dev/hooon/user/domain/entity/User.java
> +	}
저도 이 부분이 고민이었는데, ofBuyer 로 분리해주는게 더 자연스러워보여요 좋습니다~

2023-12-26 01:05 UTC, ParkJuhan94 commented on core/src/main/java/dev/hooon/user/domain/entity/UserMapper.java
> +	public static User toBuyerUser(UserJoinRequestDto userJoinRequestDto) {
바이어인 유저 엔티티를 생성하는 맵퍼 메소드인데 유저엔티티에서 Role을 정하도록 변경했습니다~

2023-12-26 01:09 UTC, ParkJuhan94 commented on core/src/main/java/dev/hooon/user/exception/UserException.java
> +public class UserException extends RuntimeException {
공통적인 ValidationException 으로 만들고 common-exception 으로 넣어놓겠습니다 !

2023-12-26 14:14 UTC, closed without merging