[feat] 사용자 로그인 api & 토큰 재발급 api & JWT 인증인가 세팅
dev-hooon/interpark pull request #59
Opened 2024-01-05 07:06 UTC by ParkJuhan94

## 📄 무엇을 개발했나요? 
- 로그인 api 와 토큰 재발급 api 는 포스트맨 테스트로 성공했습니다.
- AuthService 외에는 테스트 코드가 빠져있습니다.
- 다른 도메인에 인가 셋팅을 안해서 ci 실패로 나옵니다.
- JWT 인증인가 세팅에서는 argument resolver 와 Interceptor 를 사용했습니다.
- Refresh Token 와 Access Token 을 둘 다 활용해서 로그인을 수시로 해야하는 필요를 줄였습니다.

## 🍸 무엇을 집중적으로 리뷰해야할까요?
- 인증 인가 로직이 적절한지 리뷰 부탁드립니다. 
- argument resolver 와 Interceptor 에 대한 테스트 방식을 추천 부탁드립니다.

2024-01-07 06:42 UTC, EunChanNam requested changes
리뷰 완료했습니다~ 고생하셨어요 👏
보완할 부분이 꽤 있는거같아요
리뷰한 내용 꼼꼼히 검토 부탁드립니다~
빠르게 수정하고 빠르게 테스트코드까지 짜야될거같네요!! (진짜 촉박)

2024-01-07 06:42 UTC, EunChanNam commented on api/src/main/java/dev/hooon/auth/AuthApiController.java
> +@Slf4j
안쓰는거같은데 빼도될거같아요~

2024-01-07 06:42 UTC, EunChanNam commented on api/src/main/java/dev/hooon/auth/TokenForReIssue.java
클래스 이름이 너무 어색한데 
TokenReIssueRequest 로 가면 좋을거같아요

2024-01-07 06:42 UTC, EunChanNam commented on api/src/main/java/dev/hooon/auth/JwtAuthorizationArgumentResolver.java
> +	private String jwtHeader;
이거 꼭 프로퍼티 파일에서 가져와야하는 정보일까요? 헤더 이름정도는 노출되어도 상관없을거같아요!

2024-01-07 06:42 UTC, EunChanNam commented on api/src/main/java/dev/hooon/auth/JwtAuthorizationArgumentResolver.java
> +@Slf4j
이것도 안쓰는거같네요

2024-01-07 06:42 UTC, EunChanNam commented on api/src/main/java/dev/hooon/auth/JwtInterceptor.java
> +		}
이건 어떤 상황을 대처한 코드일까요??

2024-01-07 06:42 UTC, EunChanNam commented on api/src/test/java/dev/hooon/waitingbooking/WaitingBookingApiControllerTest.java
> +@ComponentScan(basePackages = {"dev.hooon.waitingbooking", "dev.hooon.auth.application", "dev.hooon.common.entity"})
이거 일단 제거 부탁드릴게요!

2024-01-07 06:42 UTC, EunChanNam commented on core/src/main/java/dev/hooon/auth/application/AuthService.java
> +	public Auth getAuthByRefreshToken(String refreshToken) {
public 맞을까요?

2024-01-07 06:42 UTC, EunChanNam commented on core/src/main/java/dev/hooon/auth/application/AuthService.java
> +			);
배열로 토큰을 리턴하니까 0번이 뭐고 1번이 뭔지 알수가없네요... 메소드 호출을 분리하던가 아니면 별도의 객체로 래핑해서 주는게 어떨까요?

2024-01-07 06:42 UTC, EunChanNam commented on core/src/main/java/dev/hooon/auth/application/JwtProvider.java
> +	}
생성자에서 호출하는게 더 자연스러울거같아요!

2024-01-07 06:42 UTC, EunChanNam commented on core/src/main/java/dev/hooon/auth/application/JwtProvider.java
> +	}
jwtProvider 는 토큰을 검증하고 발급하는 객체인데 authRepository 를 통해서 뭔가 수행하는건 책임이 너무 많지않나 생각이듭니다
그리고 작업을 수행하는거랑 메소드 이름이랑 너무 다른거같아요. AuthService 로 이동하는게 더 자연스러울거같아요!

2024-01-07 06:42 UTC, EunChanNam commented on core/src/main/java/dev/hooon/auth/application/JwtProvider.java
> +		}
여기서 catch 로 만료 예외랑 다른 예외 모두 던져질텐데 하나로 잡아서 INVALID 로 던지면, 클라이언트는 어떤걸 보고 토큰이 만료된지 식별하나용??

2024-01-07 06:42 UTC, EunChanNam commented on core/src/main/java/dev/hooon/auth/application/JwtProvider.java
> +		return Long.valueOf((Integer)claimsBody.getOrDefault(USER_ID, 0L));
`getOrDefault` 가 쓰인이유가 뭘까요??

2024-01-07 07:39 UTC, ParkJuhan94 commented on api/src/main/java/dev/hooon/auth/JwtAuthorizationArgumentResolver.java
> +	private String jwtHeader;
동의합니다 !

2024-01-07 07:44 UTC, ParkJuhan94 commented on api/src/main/java/dev/hooon/auth/JwtInterceptor.java
> +		}
preHandle() 이 return true 만 할 경우 소나린트 이슈가 생겨서 예외 터질때 return false 를 하나 넣어줬어요~

2024-01-07 07:47 UTC, ParkJuhan94 commented on core/src/main/java/dev/hooon/auth/application/AuthService.java
> +	public Auth getAuthByRefreshToken(String refreshToken) {
private 이 맞아보이네요!

2024-01-07 08:42 UTC, EunChanNam commented on api/src/main/java/dev/hooon/auth/JwtInterceptor.java
> +		}
이러면 예외가 터지고 예외를 계속 먹게돼서 의도대로 안흘러갈거같아요
마지막에 return true 만 있으면 소나린트가 안잡을텐데 아닌가요..?

2024-01-07 11:36 UTC, ParkJuhan94 commented on core/src/main/java/dev/hooon/auth/application/AuthService.java
> +			);
넵 별도의 객체로 리턴해서 명시적으로 나타내는게 좋겠네요~

2024-01-07 11:45 UTC, ParkJuhan94 commented on core/src/main/java/dev/hooon/auth/application/JwtProvider.java
> +	}
꼼꼼한 리뷰 감사합니다. AuthService 에서 담당하며, 관련된 리팩토링을 진행하는 것이 좋아보이네요

2024-01-09 08:28 UTC, EunChanNam approved these changes

2024-01-09 09:24 UTC, merged