[feat]: 조회 기간에 따른 예매 티켓 조회 API 추가
dev-hooon/interpark pull request #62
Opened 2024-01-07 11:00 UTC by ssssujini99

- closed #61 

## 📄 무엇을 개발했나요? 
* 조회 기간에 따른 예매 조회 API의 controller, application, repository 구현 및 각 레이어 별 테스트 구현 완료
* 각 도메인 내에서 추가로 필요한 로직들이 생겨서, 각 도메인 정책에 해당하는 메서드를 추가하였습니다
* 직접 sql 쿼리를 짠 부분에 대해서 테스트코드를 작성하고 검증하였습니다

## 🍸 무엇을 집중적으로 리뷰해야할까요?
* 네이밍, 컨벤션 확인
* native sql query 확인

2024-01-08 04:53 UTC, EunChanNam requested changes
리뷰 완료했습니다! 고생하셨어요~👏
근데 얘기좀 들어봐야할 부분이 좀 있어서 일단 Request changes 로 걸어놨습니다~

2024-01-08 04:53 UTC, EunChanNam commented on api/build.gradle
페이징 라이브러리만 컴팩트하게 받을수는 없을까요? 위에 트랜잭션처럼요!

2024-01-08 04:53 UTC, EunChanNam commented on api/src/main/java/dev/hooon/booking/BookingApiController.java
> +		@RequestParam(name = "duration") int days,
name 과 변수명 통일하면 좋지않을까요?
테스트할때 햇갈리더라고요

2024-01-08 04:53 UTC, EunChanNam commented on api/src/test/java/dev/hooon/booking/BookingApiControllerTest.java
> +			jsonPath("$.bookingList[1].currentState").isString()
타입만 검증하는것보다 값으로 검증하는게 더 의미있지 않을까요?

2024-01-08 04:53 UTC, EunChanNam commented on core/src/main/java/dev/hooon/booking/application/BookingService.java
> +		LocalDateTime createdDateTime = currentDateTime.minusDays(days);
이거 now 로 바로 호출하면 터지거든요 
일단 두고 제가 이번에 한 작업에 동적으로 주입받아서 사용할수있는거 만들어놔서 그거로 추후에 수정해주시면 좋을거같아요!

2024-01-08 04:53 UTC, EunChanNam commented on core/src/main/java/dev/hooon/booking/application/BookingService.java
> +	@Transactional
조회성 로직같은데 `readOnly` 걸면 좋을거같아요

2024-01-08 04:53 UTC, EunChanNam commented on core/src/test/java/dev/hooon/booking/infrastructure/repository/BookingJpaRepositoryTest.java
> +		Booking booking2 = Booking.of(user, show2, LocalDateTime.of(2024, 1, 1, 0, 0));
지금 당장은 문제는 없는데 언젠가는 실패할 테스트 아닐까요??(시간때문에.,..)

2024-01-08 04:53 UTC, EunChanNam commented on core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
여기는 뭘까요??
왜 auditing 안쓰시고 createAt 을 넣어주시나요??

2024-01-13 07:25 UTC, ssssujini99 commented on api/src/main/java/dev/hooon/booking/BookingApiController.java
> +		@RequestParam(name = "duration") int days,
아 api문서에 이렇게 나와있었어가지구 이렇게했는데,
통합해놓겠습니다!

2024-01-13 07:29 UTC, ssssujini99 commented on core/src/test/java/dev/hooon/booking/infrastructure/repository/BookingJpaRepositoryTest.java
> +		Booking booking2 = Booking.of(user, show2, LocalDateTime.of(2024, 1, 1, 0, 0));
아 아예 지정해준거라 상관없습니다..!! 저 두개의 상대적인 시간 비교만 필요한것이라서요!

2024-01-13 07:31 UTC, ssssujini99 commented on core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
createdAt 을 동적으로 주입받아 테스트시에 필요해서 생성자를 하나 추가하였습니다!

2024-01-13 08:11 UTC, merged